version: 0.2

env:
  parameter-store:
    Docker_Username: "/cicddemo/docker/username"
    Docker_Password: "/cicddemo/docker/password"
    Docker_Url: "/cicddemo/docker/dockerurl"

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - pip install -r day-14/simple-python-app/requirements.txt

  build:
    commands:
      - cd day-14/simple-python-app
      - echo "$Docker_Password" | docker login -u "$Docker_Username" --password-stdin "$Docker_Url"
      - docker build -t "$Docker_Url/$Docker_Username/simple-python-flask-app:latest" .
      - docker push "$Docker_Url/$Docker_Username/simple-python-flask-app:latest"

  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'
  base-directory: ../simple-python-app
